# Generated by Django 6.0 on 2025-12-16 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('Basic', 'Basic Life Support'), ('Advanced', 'Advanced Life Support'), ('ICU', 'Intensive Care Unit'), ('Wheelchair', 'Wheelchair Van')], max_length=20)),
                ('capacity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_trip', 'In Trip'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('odometer_reading', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_company', models.ForeignKey(limit_choices_to={'company_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='users.company')),
            ],
        ),
    ]
