# Generated by Django 6.0 on 2025-12-16 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='company',
            field=models.ForeignKey(blank=True, limit_choices_to={'company_type': 'client'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='users.company'),
        ),
    ]
